#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x3fcfd5aa, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x10de1094, __VMLINUX_SYMBOL_STR(release_sock) },
	{ 0x82ef608, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0x59fcade4, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x48271082, __VMLINUX_SYMBOL_STR(sock_init_data) },
	{ 0x387a31c1, __VMLINUX_SYMBOL_STR(rhashtable_walk_exit) },
	{ 0x232d18ec, __VMLINUX_SYMBOL_STR(rps_sock_flow_table) },
	{ 0xb8b6a76c, __VMLINUX_SYMBOL_STR(__percpu_counter_add) },
	{ 0xd6ee688f, __VMLINUX_SYMBOL_STR(vmalloc) },
	{ 0x6bf1c17f, __VMLINUX_SYMBOL_STR(pv_lock_ops) },
	{ 0x66d804b1, __VMLINUX_SYMBOL_STR(percpu_counter_destroy) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x60a13e90, __VMLINUX_SYMBOL_STR(rcu_barrier) },
	{ 0x79aa04a2, __VMLINUX_SYMBOL_STR(get_random_bytes) },
	{ 0x428518d9, __VMLINUX_SYMBOL_STR(rhashtable_walk_next) },
	{ 0x179651ac, __VMLINUX_SYMBOL_STR(_raw_read_lock) },
	{ 0xbe17d25d, __VMLINUX_SYMBOL_STR(dst_release) },
	{ 0xd9d3bcd3, __VMLINUX_SYMBOL_STR(_raw_spin_lock_bh) },
	{ 0x16de3b9c, __VMLINUX_SYMBOL_STR(skb_clone) },
	{ 0x88bfa7e, __VMLINUX_SYMBOL_STR(cancel_work_sync) },
	{ 0xb5dbd16a, __VMLINUX_SYMBOL_STR(__percpu_counter_sum) },
	{ 0xb84bb8f2, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xfa9a1798, __VMLINUX_SYMBOL_STR(__dst_destroy_metrics_generic) },
	{ 0x999e8297, __VMLINUX_SYMBOL_STR(vfree) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x7a2af7b4, __VMLINUX_SYMBOL_STR(cpu_number) },
	{ 0x87ed6b52, __VMLINUX_SYMBOL_STR(rhashtable_insert_slow) },
	{ 0x71ac8156, __VMLINUX_SYMBOL_STR(rhashtable_walk_init) },
	{ 0xd643f584, __VMLINUX_SYMBOL_STR(dst_alloc) },
	{ 0x9b39cc26, __VMLINUX_SYMBOL_STR(sk_common_release) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x17270715, __VMLINUX_SYMBOL_STR(skb_trim) },
	{ 0x7e80db77, __VMLINUX_SYMBOL_STR(sock_no_sendpage) },
	{ 0x836d5b9, __VMLINUX_SYMBOL_STR(__pskb_pull_tail) },
	{ 0x7cd341f0, __VMLINUX_SYMBOL_STR(sock_get_timestamp) },
	{ 0x73d34f16, __VMLINUX_SYMBOL_STR(rhashtable_walk_start) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xfc9ff755, __VMLINUX_SYMBOL_STR(rhashtable_free_and_destroy) },
	{ 0x178eb77b, __VMLINUX_SYMBOL_STR(__cpu_possible_mask) },
	{ 0xe26d8b83, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0x5d299feb, __VMLINUX_SYMBOL_STR(sk_alloc) },
	{ 0x11089ac7, __VMLINUX_SYMBOL_STR(_ctype) },
	{ 0x764b99b6, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0x7b4886bd, __VMLINUX_SYMBOL_STR(rhashtable_insert_rehash) },
	{ 0xe9174032, __VMLINUX_SYMBOL_STR(rhashtable_walk_stop) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x3c3fce39, __VMLINUX_SYMBOL_STR(__local_bh_enable_ip) },
	{ 0x525662d5, __VMLINUX_SYMBOL_STR(lock_sock_nested) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xe2f425e7, __VMLINUX_SYMBOL_STR(rps_cpu_mask) },
	{ 0x18cc0e9a, __VMLINUX_SYMBOL_STR(dst_discard_out) },
	{ 0xaafdc258, __VMLINUX_SYMBOL_STR(strcasecmp) },
	{ 0x8afaebe7, __VMLINUX_SYMBOL_STR(nla_put) },
	{ 0x1b3e581a, __VMLINUX_SYMBOL_STR(__sk_mem_reclaim) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xe937c89d, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xe8db8dd2, __VMLINUX_SYMBOL_STR(_raw_write_lock) },
	{ 0x76ef438d, __VMLINUX_SYMBOL_STR(rtnl_register) },
	{ 0xccc68a5c, __VMLINUX_SYMBOL_STR(dev_remove_pack) },
	{ 0xc2cdbf1, __VMLINUX_SYMBOL_STR(synchronize_sched) },
	{ 0x5240ee7, __VMLINUX_SYMBOL_STR(percpu_counter_batch) },
	{ 0x69ee35cc, __VMLINUX_SYMBOL_STR(init_net) },
	{ 0x4e0964e3, __VMLINUX_SYMBOL_STR(__dev_get_by_index) },
	{ 0x42160169, __VMLINUX_SYMBOL_STR(flush_workqueue) },
	{ 0xf11543ff, __VMLINUX_SYMBOL_STR(find_first_zero_bit) },
	{ 0x4353e2c6, __VMLINUX_SYMBOL_STR(dst_cow_metrics_generic) },
	{ 0x5f007e8f, __VMLINUX_SYMBOL_STR(proto_register) },
	{ 0x347013de, __VMLINUX_SYMBOL_STR(nla_validate) },
	{ 0xbba70a2d, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_bh) },
	{ 0x5b3648a0, __VMLINUX_SYMBOL_STR(sock_get_timestampns) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0xffb28cdc, __VMLINUX_SYMBOL_STR(sock_register) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x3e9613b4, __VMLINUX_SYMBOL_STR(kfree_skb) },
	{ 0xf7eae9e0, __VMLINUX_SYMBOL_STR(proto_unregister) },
	{ 0x6b2dc060, __VMLINUX_SYMBOL_STR(dump_stack) },
	{ 0x90047aa7, __VMLINUX_SYMBOL_STR(sock_alloc_send_skb) },
	{ 0xf8343c05, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0xb905c66, __VMLINUX_SYMBOL_STR(__percpu_counter_init) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0xc31374f6, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xac7ae8ad, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0xf6ebc03b, __VMLINUX_SYMBOL_STR(net_ratelimit) },
	{ 0xc2e59668, __VMLINUX_SYMBOL_STR(rhashtable_init) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x643e0ce5, __VMLINUX_SYMBOL_STR(call_rcu_sched) },
	{ 0x21bff664, __VMLINUX_SYMBOL_STR(___pskb_trim) },
	{ 0x62737e1d, __VMLINUX_SYMBOL_STR(sock_unregister) },
	{ 0x579e0bf5, __VMLINUX_SYMBOL_STR(rtnl_unregister_all) },
	{ 0x63c4d61f, __VMLINUX_SYMBOL_STR(__bitmap_weight) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x4dc0854, __VMLINUX_SYMBOL_STR(dev_add_pack) },
	{ 0xb0e602eb, __VMLINUX_SYMBOL_STR(memmove) },
	{ 0xfb707294, __VMLINUX_SYMBOL_STR(consume_skb) },
	{ 0x85670f1d, __VMLINUX_SYMBOL_STR(rtnl_is_locked) },
	{ 0x9bc59e3c, __VMLINUX_SYMBOL_STR(skb_put) },
	{ 0x7f1d329c, __VMLINUX_SYMBOL_STR(__nlmsg_put) },
	{ 0xe914e41e, __VMLINUX_SYMBOL_STR(strcpy) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=";


MODULE_INFO(srcversion, "CA16F9D31089CA97F9D2B89");
